# Generated by Django 4.2.7 on 2026-07-09 21:48

from django.db import migrations, models
import xmu.models


class Migration(migrations.Migration):

    dependencies = [
        ('xmu', '0015_uploadedfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backgroundimage',
            options={'ordering': ['-weight', '-created_at'], 'verbose_name': '背景配置', 'verbose_name_plural': '背景配置'},
        ),
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': '联系留言', 'verbose_name_plural': '联系留言'},
        ),
        migrations.AlterModelOptions(
            name='galleryimage',
            options={'ordering': ['-weight', '-created_at'], 'verbose_name': '科研图库', 'verbose_name_plural': '科研图库'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['-position', '-weight', 'id'], 'verbose_name': '团队成员', 'verbose_name_plural': '团队成员'},
        ),
        migrations.AlterModelOptions(
            name='paper',
            options={'ordering': ['-published_date', '-created_at'], 'verbose_name': '论文', 'verbose_name_plural': '论文'},
        ),
        migrations.AlterModelOptions(
            name='researchdirection',
            options={'ordering': ['-weight', 'id'], 'verbose_name': '研究方向', 'verbose_name_plural': '研究方向'},
        ),
        migrations.AlterModelOptions(
            name='resultimage',
            options={'ordering': ['-weight', '-created_at'], 'verbose_name': '研究成果', 'verbose_name_plural': '研究成果'},
        ),
        migrations.AlterModelOptions(
            name='uploadedfile',
            options={'ordering': ['-uploaded_at'], 'verbose_name': '上传文件', 'verbose_name_plural': '上传文件'},
        ),
        migrations.AddField(
            model_name='member',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='paper',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='researchdirection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='researchdirection',
            name='weight',
            field=models.IntegerField(db_index=True, default=0, verbose_name='权重'),
        ),
        migrations.AlterField(
            model_name='backgroundimage',
            name='author',
            field=models.CharField(blank=True, default='Isaac Newton', max_length=100, null=True, verbose_name='名言作者'),
        ),
        migrations.AlterField(
            model_name='backgroundimage',
            name='avatar',
            field=models.ImageField(blank=True, default='logo.jpg', null=True, upload_to='bg/', verbose_name='背景图片'),
        ),
        migrations.AlterField(
            model_name='backgroundimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='backgroundimage',
            name='quote',
            field=models.TextField(blank=True, default='If I have seen further it is by standing on the shoulders of giants.', null=True, verbose_name='名言'),
        ),
        migrations.AlterField(
            model_name='backgroundimage',
            name='weight',
            field=models.IntegerField(db_index=True, default=0, verbose_name='权重'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(verbose_name='留言内容'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(max_length=100, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='图片描述'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to='gallery_images/', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='weight',
            field=models.IntegerField(db_index=True, default=0, verbose_name='权重'),
        ),
        migrations.AlterField(
            model_name='member',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar.jpg', null=True, upload_to='avatars/', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='member',
            name='degree',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='学位'),
        ),
        migrations.AlterField(
            model_name='member',
            name='education',
            field=models.TextField(blank=True, null=True, verbose_name='教育背景'),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=100, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='member',
            name='position',
            field=models.CharField(choices=[('Professor', 'Professor'), ('Member', 'Member')], db_index=True, default='Member', max_length=10, verbose_name='职位'),
        ),
        migrations.AlterField(
            model_name='member',
            name='weight',
            field=models.IntegerField(db_index=True, default=0, verbose_name='权重'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='authors',
            field=models.CharField(max_length=300, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='link',
            field=models.URLField(max_length=500, verbose_name='论文链接'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='published_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='发表日期'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.CharField(max_length=200, verbose_name='论文名称'),
        ),
        migrations.AlterField(
            model_name='researchdirection',
            name='direction_name',
            field=models.TextField(verbose_name='研究方向'),
        ),
        migrations.AlterField(
            model_name='resultimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='resultimage',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='图片描述'),
        ),
        migrations.AlterField(
            model_name='resultimage',
            name='image',
            field=models.ImageField(upload_to='result_images/', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='resultimage',
            name='weight',
            field=models.IntegerField(db_index=True, default=0, verbose_name='权重'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to=xmu.models.user_directory_path, verbose_name='文件'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='title',
            field=models.CharField(max_length=255, verbose_name='文件标题'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='上传时间'),
        ),
    ]
