# Generated by Django 4.2.7 on 2026-07-15 14:34

from django.db import migrations, models
import xmu.models


class Migration(migrations.Migration):

    dependencies = [
        ('xmu', '0016_alter_backgroundimage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeHoleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(db_index=True, max_length=36, unique=True, verbose_name='图片唯一标识')),
                ('image', models.ImageField(upload_to=xmu.models.treehole_image_path, verbose_name='图片')),
                ('filename', models.CharField(blank=True, max_length=255, verbose_name='原始文件名')),
                ('size', models.IntegerField(default=0, verbose_name='文件大小')),
                ('width', models.IntegerField(default=0, verbose_name='图片宽度')),
                ('height', models.IntegerField(default=0, verbose_name='图片高度')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '树洞图片',
                'verbose_name_plural': '树洞图片',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TreeHoleMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, max_length=36, unique=True, verbose_name='留言唯一标识')),
                ('content', models.TextField(blank=True, verbose_name='留言内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='创建时间')),
                ('images', models.ManyToManyField(blank=True, to='xmu.treeholeimage', verbose_name='关联图片')),
            ],
            options={
                'verbose_name': '树洞留言',
                'verbose_name_plural': '树洞留言',
                'ordering': ['-created_at'],
            },
        ),
    ]
