# Generated by Django 4.2.7 on 2026-07-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmu', '0017_treeholeimage_treeholemessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treeholemessage',
            name='images',
        ),
        migrations.AddField(
            model_name='treeholemessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='treehole/', verbose_name='图片'),
        ),
    ]
