# Generated by Django 4.2.7 on 2026-07-15 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xmu', '0018_remove_treeholemessage_images_treeholemessage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeHoleContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.CharField(db_index=True, max_length=36, unique=True, verbose_name='内容唯一标识')),
                ('content', models.TextField(verbose_name='留言内容')),
                ('word_count', models.IntegerField(default=0, verbose_name='字数')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '树洞内容',
                'verbose_name_plural': '树洞内容',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='treeholemessage',
            name='content',
        ),
        migrations.AddField(
            model_name='treeholemessage',
            name='name',
            field=models.CharField(default='匿名', max_length=50, verbose_name='姓名'),
        ),
        migrations.AddField(
            model_name='treeholemessage',
            name='content_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='xmu.treeholecontent', verbose_name='内容引用'),
        ),
    ]
